### ISSUE TITLE
Disconnects players upon login.

### ISSUE THREAD

**Issue by VergilPrime** [steakteam/CHProtocol#3]
With this extension loaded on my server, players get booted upon login.

Running Spigot 1.15.2 server on a BungeeCord proxy. Any ideas?

**Comment by entrypointkr** [comment]
I can't reproduce it. Have you tried servers(not bungeecord) in offline mode? and kick message, server logs needs

**Comment by entrypointkr** [comment]
closing as no response was provided. if it still a matter, please reopen this issue.

**Comment by VergilPrime** [comment]
Sorry, I don't check notifications on Github so I missed this. I am working on updating to 1.16 right now so I don't have a dev server besides the one I am using, I can test again when I finish that.

**Comment by entrypointkr** [comment]
No problem. Okay, feel free to let me know if you got trouble with CHProtocol.
